### PR TITLE
Added some methods from std::option::Option

### PR DESCRIPTION
**Pull request by rnleach**
Added the `and` and `and_then` methods. I use these a lot. I also bumped the version since I added functionality. Please check `Cargo.toml` to make sure I did that right, I'm not the best at semver.

If/when this gets accepted, would it be possible to get the new version pushed to crates.io?

Thanks!

### CODE REVIEW

**Comment by rnleach** [comment]
Ok, I rebased after the other pull requests were merged. Not sure I did it correctly. Let me know, I can start a new PR from scratch if needed. I'm still a novice with Git. Thanks.

**Comment by llogiq** [comment]
Thank you for the PR! Should we inline the methods?

**Comment by rnleach** [comment]
Good catch. Done.

**Review by llogiq — APPROVED** [review]

**Comment by llogiq** [comment]
Thanks again!

**Comment by rnleach** [comment]
Glad to contribute! (These PR's are my first for rust.) I prefer to pull
crates from crates.io and not github though, could you possibly update on
crates too? I see the added `or` methods aren't in the version on crates.io
either.

Thanks,

**Comment by llogiq** [comment]
Sure, I'll do that later today (I'd do it now, but unfortunately didn't get a seat on my commute today, so I cannot use my notebook right now).

**Pull request merged**
